#!/bin/bash
# multi-model-comparison.sh - Same question to multiple models
#
# This script demonstrates using parallel execution to send the same
# question to multiple AI models simultaneously and compare their responses.
#
# Great for:
#   - Comparing model capabilities
#   - Benchmarking response quality
#   - Finding the best model for your use case
#   - A/B testing prompts across models
#
# Prerequisites:
#   - agentpipe installed and in PATH
#   - OPENROUTER_API_KEY environment variable (for OpenRouter models)
#   - Or: Individual API keys for direct API access
#
# Usage:
#   ./multi-model-comparison.sh "Explain quantum computing in simple terms"
#   ./multi-model-comparison.sh "Write a haiku about coding"
#
# Features demonstrated:
#   - parallel execution (all models respond simultaneously)
#   - Multiple models in single conversation
#   - Headless mode for clean output
#   - Cost and token tracking

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMP_CONFIG=$(mktemp)

# Default question
QUESTION="${1:-Explain the concept of recursion to a beginner programmer. Include a simple example.}"

# Cleanup temp file on exit
trap "rm -f $TEMP_CONFIG" EXIT

# Check for required environment variable
if [ -z "$OPENROUTER_API_KEY" ]; then
    echo "Error: OPENROUTER_API_KEY environment variable not set"
    echo ""
    echo "Get an API key at: https://openrouter.ai"
    echo "Then run: export OPENROUTER_API_KEY=your-key-here"
    exit 1
fi

echo "========================================"
echo "  Multi-Model Comparison (v2 Parallel)"
echo "========================================"
echo ""
echo "Question: $QUESTION"
echo ""
echo "Models being compared:"
echo "  1. GPT-4o (OpenAI via OpenRouter)"
echo "  2. Claude 3.5 Sonnet (Anthropic via OpenRouter)"
echo "  3. Gemini 1.5 Pro (Google via OpenRouter)"
echo ""
echo "All models will respond in parallel..."
echo ""

# Create a dynamic config with multiple OpenRouter agents
cat > "$TEMP_CONFIG" << 'EOF'
# Multi-model comparison configuration
# Generated by multi-model-comparison.sh

conversation:
  timeout: 120s
  mode: parallel

agents:
  - id: gpt4o
    type: openrouter
    adapter: openrouter
    name: "GPT-4o"
    model: openai/gpt-4o
    config:
      system_prompt: |
        You are a helpful AI assistant. Provide clear, concise responses.
        When explaining concepts, use analogies and examples.
      temperature: 0.7
      max_tokens: 1000
      api_key_env: OPENROUTER_API_KEY

  - id: claude-sonnet
    type: openrouter
    adapter: openrouter
    name: "Claude 3.5 Sonnet"
    model: anthropic/claude-3.5-sonnet
    config:
      system_prompt: |
        You are a helpful AI assistant. Provide clear, concise responses.
        When explaining concepts, use analogies and examples.
      temperature: 0.7
      max_tokens: 1000
      api_key_env: OPENROUTER_API_KEY

  - id: gemini-pro
    type: openrouter
    adapter: openrouter
    name: "Gemini 1.5 Pro"
    model: google/gemini-pro-1.5
    config:
      system_prompt: |
        You are a helpful AI assistant. Provide clear, concise responses.
        When explaining concepts, use analogies and examples.
      temperature: 0.7
      max_tokens: 1000
      api_key_env: OPENROUTER_API_KEY

persistence:
  auto_save: false

logging:
  level: info
EOF

# Run the comparison
echo "========================================"
echo "  RESPONSES"
echo "========================================"
echo ""

# Pipe the question to v2 headless mode
echo "$QUESTION" | agentpipe run \
    --config "$TEMP_CONFIG" \
    --auto-save=false \
    --timeout 120

echo ""
echo "========================================"
echo "  COMPARISON COMPLETE"
echo "========================================"
echo ""
echo "Tips for comparing responses:"
echo "  - Look at how each model structures its explanation"
echo "  - Compare the examples they choose"
echo "  - Note differences in verbosity and clarity"
echo "  - Check token usage and cost in the summary above"
echo ""
echo "To save this comparison, redirect output to a file:"
echo "  $0 \"$QUESTION\" > comparison.txt 2>&1"
